name: workflow for Codecov
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
         os: [ubuntu-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.7'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pip install numpy
        pip install -U scikit-learn
        pip install denmune
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: 'a4d6a0d3-8b50-4164-8270-c3da50caa3bc'
        files: ./coverage.xml
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        flags: unittests
        name: codecov-umbrella
        verbose: true
